<?php

namespace Bazofather\Bale;

use Bazofather\Interface\BazofatherBase;

class BaleBot extends BazofatherBase
{

    /**
     * Bale bot file api url
     * for download - upload files
     *
     * @var string
     */
    protected string $base_file_url;

    public function __construct()
    {
        parent::__construct();

        // https://tapi.bale.ai/bot{token}/sendMessage
        $this->setBaseUrl("https://tapi.bale.ai/");
    }

    public function getUpdates(): array
    {
        return parent::getUpdates(); // TODO: Change the autogenerated stub
    }


}
